---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-app-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: web-app-v1
              servicePort: 80
status:
  loadBalancer:
    ingress:
      - hostname: k4s-master
